Guile-Debbugs --- Guile bindings for Debbugs
Copyright © 2017, 2018 Ricardo Wurmus <rekado@elephly.net>
See the end of the file for license conditions.

* What is this?

This is an attempt to provide Guile bindings for the debbugs bug
tracker.  See the Info manual (=doc/guile-debbugs.info=) for examples
and documentation.  (You will have to build it first.)

* Missing features

+ convenience procedures for =<bug>= records (e.g. =bug-done?=)
+ monadic interface

* Known problems

+ Guile 2.2.2 has a bug in “(web client)”, which prevents HTTPS connections from being established.  This is fixed in Guile 2.2.3.

* Hacking

#+BEGIN_SRC bash
guix environment --ad-hoc autoconf automake make texinfo pkg-config guile@2.2
./bootstrap.sh
./configure
make
#+END_SRC

* License

This file is part of Guile-Debbugs.

Guile-Debbugs is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the
License, or (at your option) any later version.

Guile-Debbugs is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Guile-Debbugs.  If not, see <http://www.gnu.org/licenses/>.
